import Link from "next/link";
import type { Metadata } from "next";
import { site } from "@/config/site";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft, Scale, AlertTriangle, CreditCard, Image as ImageIcon } from "lucide-react";

export const runtime = "edge";

export async function generateMetadata(props: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const params = await props.params;
  const { locale } = params;
  const isZh = locale === "zh";

  const title = isZh ? `服务条款 | ${site.siteName}` : `Terms of Service | ${site.siteName}`;
  const description = isZh
    ? "使用本服务前请阅读条款，包括生成内容、积分计费、以及禁止内容。"
    : "Read the terms before using the service, including generated content, credits billing, and prohibited content.";

  const ogImage = new URL(site.ogImagePath, site.siteUrl).toString();

  return {
    title,
    description,
    alternates: { canonical: `/${locale}/terms`, languages: { en: "/en/terms", zh: "/zh/terms", "x-default": "/en/terms" } },
    openGraph: {
      title,
      description,
      type: "website",
      url: new URL(`/${locale}/terms`, site.siteUrl).toString(),
      siteName: site.siteName,
      images: [{ url: ogImage, width: 512, height: 512, alt: site.siteName }],
    },
    twitter: { card: "summary_large_image", title, description, images: [ogImage] },
  };
}

export default async function TermsPage(props: { params: Promise<{ locale: string }> }) {
  const params = await props.params;
  const { locale } = params;
  const isZh = locale === "zh";
  const localePrefix = `/${locale}`;

  return (
    <div className="min-h-screen bg-background">
      <div className="border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container px-4 md:px-6 py-4">
          <Button asChild variant="ghost" size="sm" className="gap-2">
            <Link href={localePrefix}>
              <ArrowLeft className="h-4 w-4" />
              {isZh ? "返回首页" : "Back to Home"}
            </Link>
          </Button>
        </div>
      </div>

      <div className="container px-4 md:px-6 py-16">
        <div className="max-w-4xl mx-auto space-y-8">
          <div className="text-center space-y-3">
            <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">{isZh ? "服务条款" : "Terms of Service"}</h1>
            <p className="text-muted-foreground">
              {isZh ? "这是第一版简化条款，后续会更新。" : "This is a simplified v1 and may be updated."}
            </p>
          </div>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <ImageIcon className="w-5 h-5 text-primary" />
                {isZh ? "你上传的内容" : "Your Uploads"}
              </CardTitle>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground leading-relaxed space-y-3">
              <p>
                {isZh
                  ? "你必须拥有上传图片的合法权利，并确保内容不侵犯他人权利。"
                  : "You must have the legal right to upload the images and ensure they do not infringe others’ rights."}
              </p>
              <p>
                {isZh
                  ? "禁止上传违法、侵权、或包含敏感个人信息的内容。"
                  : "Do not upload illegal, infringing, or sensitive personal information."}
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Scale className="w-5 h-5 text-primary" />
                {isZh ? "生成内容" : "Generated Content"}
              </CardTitle>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground leading-relaxed space-y-3">
              <p>
                {isZh
                  ? "生成结果由 AI 自动生成，可能不准确或不符合预期。你应自行判断并承担使用风险。"
                  : "Outputs are generated by AI and may be inaccurate or unexpected. You use them at your own risk."}
              </p>
              <p>
                {isZh
                  ? "我们不保证生成结果一定可用于商业用途；如需商业使用请自行核实权利与合规。"
                  : "We don’t guarantee outputs are fit for commercial use; verify rights and compliance yourself."}
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <CreditCard className="w-5 h-5 text-primary" />
                {isZh ? "积分与付费" : "Credits & Payments"}
              </CardTitle>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground leading-relaxed space-y-3">
              <p>
                {isZh
                  ? "生成图片会消耗积分。免费额度与定价可能随时调整。"
                  : "Generating images consumes credits. Free allowance and pricing may change."}
              </p>
              <p>
                {isZh
                  ? "付款与订阅由支付服务商处理。若发生支付问题，请优先联系支付服务商或我们的支持渠道。"
                  : "Payments and subscriptions are processed by a payment provider. Contact them or our support for billing issues."}
              </p>
            </CardContent>
          </Card>

          <div className="rounded-xl border border-amber-200 bg-amber-50 text-amber-900 dark:border-amber-900/40 dark:bg-amber-950/20 dark:text-amber-100 p-5 flex gap-3">
            <AlertTriangle className="w-5 h-5 mt-0.5" />
            <div className="text-sm leading-relaxed">
              {isZh
                ? "本服务按“现状”提供。我们可能随时更新或停止某些功能。"
                : "The service is provided “as is”. We may update or discontinue features at any time."}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

