import type { LandingPageSlug } from "@/config/landing-pages";

export type GalleryItem = {
  id: string;
  useCase: LandingPageSlug;
  slug: string;
  category: string;
  title: string;
  titleZh: string;
  description: string;
  descriptionZh: string;
  alt: string;
  altZh: string;
  afterImage: string;
  beforeThumb: string;
  videoUrl: string;
  durationLabel: string;
  aspectRatioLabel: string;
  promptLabel: string;
};

const SHARED_AFTER = "/images/gallery/hero-after.png";
const SHARED_BEFORE = "/images/gallery/hero-before.png";

const kieSeedanceSamples: GalleryItem[] = [
  {
    id: "kie-seedance-01",
    useCase: "reference-video-generator",
    slug: "reference-video-generator",
    category: "Character",
    title: "Silver-haired character close-up",
    titleZh: "银发角色特写",
    description: "A tight character shot for testing Seedance 2 identity, lighting, and facial-detail continuity.",
    descriptionZh: "用于观察 Seedance 2 在角色身份、光影和面部细节连续性上的表现。",
    alt: "Kie Seedance 2 sample showing a silver-haired character close-up.",
    altZh: "Kie Seedance 2 银发角色特写视频样例。",
    afterImage: "/images/gallery/kie/kie-seedance-01.jpg",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/kie/kie-seedance-01.mp4",
    durationLabel: "14s",
    aspectRatioLabel: "16:9",
    promptLabel: "Kie sample",
  },
  {
    id: "kie-seedance-02",
    useCase: "dance-motion-transfer",
    slug: "dance-motion-transfer",
    category: "Motion",
    title: "Action replication workflow",
    titleZh: "动作复刻工作流",
    description: "A reference-led sample that shows how motion, pose, and character intent can be separated during generation.",
    descriptionZh: "展示如何把动作、姿态和角色意图拆开控制的参考驱动样例。",
    alt: "Kie Seedance 2 sample showing an action replication workflow.",
    altZh: "Kie Seedance 2 动作复刻工作流视频样例。",
    afterImage: "/images/gallery/kie/kie-seedance-02.jpg",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/kie/kie-seedance-02.mp4",
    durationLabel: "14s",
    aspectRatioLabel: "16:9",
    promptLabel: "Motion ref",
  },
  {
    id: "kie-seedance-03",
    useCase: "dance-motion-transfer",
    slug: "dance-motion-transfer",
    category: "Action",
    title: "Studio fight motion reference",
    titleZh: "棚拍动作参考",
    description: "A fast movement clip for evaluating timing, body mechanics, and action continuity.",
    descriptionZh: "适合观察节奏、肢体运动和动作连续性的快速动作样例。",
    alt: "Kie Seedance 2 sample showing a studio fight motion reference.",
    altZh: "Kie Seedance 2 棚拍动作参考视频样例。",
    afterImage: "/images/gallery/kie/kie-seedance-03.jpg",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/kie/kie-seedance-03.mp4",
    durationLabel: "11s",
    aspectRatioLabel: "16:9",
    promptLabel: "Action ref",
  },
  {
    id: "kie-seedance-04",
    useCase: "storyboard-to-video",
    slug: "storyboard-to-video",
    category: "Sci-fi",
    title: "Sci-fi visor close-up",
    titleZh: "科幻目镜特写",
    description: "A cinematic close-up for testing Seedance 2 mood, reflective surfaces, and micro camera movement.",
    descriptionZh: "用于测试 Seedance 2 在氛围、反光材质和细微镜头运动上的表现。",
    alt: "Kie Seedance 2 sample showing a sci-fi visor close-up.",
    altZh: "Kie Seedance 2 科幻目镜特写视频样例。",
    afterImage: "/images/gallery/kie/kie-seedance-04.jpg",
    beforeThumb: SHARED_AFTER,
    videoUrl: "/videos/gallery/kie/kie-seedance-04.mp4",
    durationLabel: "15s",
    aspectRatioLabel: "16:9",
    promptLabel: "Cinematic",
  },
  {
    id: "kie-seedance-05",
    useCase: "image-to-video",
    slug: "image-to-video",
    category: "Anime",
    title: "Anime portrait motion",
    titleZh: "动漫角色动态特写",
    description: "A stylized portrait example for turning a strong still-frame look into a moving Seedance 2 clip.",
    descriptionZh: "适合展示如何把强风格静帧角色推进成动态视频的动漫样例。",
    alt: "Kie Seedance 2 sample showing anime portrait motion.",
    altZh: "Kie Seedance 2 动漫角色动态特写视频样例。",
    afterImage: "/images/gallery/kie/kie-seedance-05.jpg",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/kie/kie-seedance-05.mp4",
    durationLabel: "15s",
    aspectRatioLabel: "16:9",
    promptLabel: "Image seed",
  },
  {
    id: "kie-seedance-06",
    useCase: "video-extension",
    slug: "video-extension",
    category: "Cinematic",
    title: "Neon city drive",
    titleZh: "霓虹城市车窗镜头",
    description: "A moody city shot that works well for extending atmosphere, lighting, and camera direction.",
    descriptionZh: "适合观察氛围、灯光和镜头方向延展能力的城市夜景样例。",
    alt: "Kie Seedance 2 sample showing a neon city drive.",
    altZh: "Kie Seedance 2 霓虹城市车窗镜头视频样例。",
    afterImage: "/images/gallery/kie/kie-seedance-06.jpg",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/kie/kie-seedance-06.mp4",
    durationLabel: "15s",
    aspectRatioLabel: "16:9",
    promptLabel: "Scene extend",
  },
  {
    id: "kie-seedance-07",
    useCase: "ai-short-drama-maker",
    slug: "ai-short-drama-maker",
    category: "Action",
    title: "Autumn battle chase",
    titleZh: "秋林追逐战斗",
    description: "A full action sample for judging blocking, camera travel, and scene momentum.",
    descriptionZh: "适合判断走位、运镜和场景动势的完整动作样例。",
    alt: "Kie Seedance 2 sample showing an autumn battle chase.",
    altZh: "Kie Seedance 2 秋林追逐战斗视频样例。",
    afterImage: "/images/gallery/kie/kie-seedance-07.jpg",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/kie/kie-seedance-07.mp4",
    durationLabel: "13s",
    aspectRatioLabel: "16:9",
    promptLabel: "Action clip",
  },
  {
    id: "kie-seedance-08",
    useCase: "storyboard-to-video",
    slug: "storyboard-to-video",
    category: "Sci-fi",
    title: "Reflective visor alternate",
    titleZh: "反光目镜变化镜头",
    description: "A second sci-fi close-up that is useful for comparing shot consistency and visual texture.",
    descriptionZh: "另一条科幻特写样例，适合对比镜头一致性和画面材质。",
    alt: "Kie Seedance 2 sample showing an alternate reflective visor close-up.",
    altZh: "Kie Seedance 2 反光目镜变化镜头视频样例。",
    afterImage: "/images/gallery/kie/kie-seedance-08.jpg",
    beforeThumb: SHARED_AFTER,
    videoUrl: "/videos/gallery/kie/kie-seedance-08.mp4",
    durationLabel: "15s",
    aspectRatioLabel: "16:9",
    promptLabel: "Cinematic",
  },
  {
    id: "kie-seedance-09",
    useCase: "product-ad-generator",
    slug: "product-ad-generator",
    category: "Lifestyle",
    title: "Balcony fabric reveal",
    titleZh: "阳台布料生活镜头",
    description: "A soft lifestyle shot for exploring natural light, fabric movement, and product-ad pacing.",
    descriptionZh: "适合探索自然光、布料运动和生活方式广告节奏的柔和样例。",
    alt: "Kie Seedance 2 sample showing a balcony fabric reveal.",
    altZh: "Kie Seedance 2 阳台布料生活镜头视频样例。",
    afterImage: "/images/gallery/kie/kie-seedance-09.jpg",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/kie/kie-seedance-09.mp4",
    durationLabel: "08s",
    aspectRatioLabel: "16:9",
    promptLabel: "Product mood",
  },
  {
    id: "kie-seedance-10",
    useCase: "storyboard-to-video",
    slug: "storyboard-to-video",
    category: "Storyboard",
    title: "Ink fashion storyboard",
    titleZh: "水墨时装分镜",
    description: "A stylized storyboard example for converting illustration language into video direction.",
    descriptionZh: "用于展示如何把插画语言转换成视频镜头方向的风格化分镜样例。",
    alt: "Kie Seedance 2 sample showing an ink fashion storyboard.",
    altZh: "Kie Seedance 2 水墨时装分镜视频样例。",
    afterImage: "/images/gallery/kie/kie-seedance-10.jpg",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/kie/kie-seedance-10.mp4",
    durationLabel: "10s",
    aspectRatioLabel: "16:9",
    promptLabel: "Storyboard",
  },
  {
    id: "kie-seedance-11",
    useCase: "dance-motion-transfer",
    slug: "dance-motion-transfer",
    category: "Motion",
    title: "Fencing motion transfer",
    titleZh: "击剑动作迁移",
    description: "A controlled motion-transfer sample for testing opposing movement, timing, and clear silhouettes.",
    descriptionZh: "用于测试对抗动作、时机和清晰轮廓的受控动作迁移样例。",
    alt: "Kie Seedance 2 sample showing fencing motion transfer.",
    altZh: "Kie Seedance 2 击剑动作迁移视频样例。",
    afterImage: "/images/gallery/kie/kie-seedance-11.jpg",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/kie/kie-seedance-11.mp4",
    durationLabel: "14s",
    aspectRatioLabel: "16:9",
    promptLabel: "Motion ref",
  },
  {
    id: "kie-seedance-12",
    useCase: "dance-motion-transfer",
    slug: "dance-motion-transfer",
    category: "Motion",
    title: "Fencing timing variation",
    titleZh: "击剑节奏变化",
    description: "A timing variation that helps compare how reference motion behaves across similar action setups.",
    descriptionZh: "用于对比相似动作场景下参考动作和节奏变化的样例。",
    alt: "Kie Seedance 2 sample showing a fencing timing variation.",
    altZh: "Kie Seedance 2 击剑节奏变化视频样例。",
    afterImage: "/images/gallery/kie/kie-seedance-12.jpg",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/kie/kie-seedance-12.mp4",
    durationLabel: "14s",
    aspectRatioLabel: "16:9",
    promptLabel: "Motion ref",
  },
  {
    id: "kie-seedance-13",
    useCase: "ai-short-drama-maker",
    slug: "ai-short-drama-maker",
    category: "Drama",
    title: "Cinematic eye close-up",
    titleZh: "电影感眼部特写",
    description: "A dramatic close-up for evaluating mood, focus shifts, and story tension in short-form clips.",
    descriptionZh: "适合观察情绪、焦点变化和短片叙事张力的电影感特写样例。",
    alt: "Kie Seedance 2 sample showing a cinematic eye close-up.",
    altZh: "Kie Seedance 2 电影感眼部特写视频样例。",
    afterImage: "/images/gallery/kie/kie-seedance-13.jpg",
    beforeThumb: SHARED_AFTER,
    videoUrl: "/videos/gallery/kie/kie-seedance-13.mp4",
    durationLabel: "15s",
    aspectRatioLabel: "16:9",
    promptLabel: "Drama clip",
  },
];

export const galleryItems: GalleryItem[] = [
  {
    id: "seedance-hero-4",
    useCase: "image-to-video",
    slug: "image-to-video",
    category: "Performance",
    title: "Balance beam motion study",
    titleZh: "平衡木动作镜头",
    description: "A compact performance clip that works well as a keyframe-to-motion example for Seedance 2 image-to-video workflows.",
    descriptionZh: "一条更适合图生视频场景的动作样片：先锁住角色起始画面，再把运动感逐步推出来。",
    alt: "Seedance 2 video sample showing a gymnast walking across a balance beam.",
    altZh: "用于展示 Seedance 2 图生视频工作流的平衡木动作视频样例。",
    afterImage: "/images/gallery/custom/seedance-hero-4.png",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/seedance-hero-4.mp4",
    durationLabel: "05s",
    aspectRatioLabel: "16:9",
    promptLabel: "Image seed",
  },
  {
    id: "seedance-hero-6",
    useCase: "ai-short-drama-maker",
    slug: "ai-short-drama-maker",
    category: "Narrative",
    title: "Street rush sequence",
    titleZh: "街头追逐片段",
    description: "A fast narrative moment that fits short-drama, storyboard, and text-led video ideation with stronger urgency.",
    descriptionZh: "一条更有叙事冲突感的街头奔跑样片，适合短剧、分镜预演和文本驱动的镜头构思。",
    alt: "Seedance 2 narrative video sample showing a man running through a crowded street.",
    altZh: "用于展示 Seedance 2 短剧与叙事镜头生成的街头奔跑视频样例。",
    afterImage: "/images/gallery/custom/seedance-hero-6.png",
    beforeThumb: SHARED_AFTER,
    videoUrl: "/videos/gallery/seedance-hero-6.mp4",
    durationLabel: "05s",
    aspectRatioLabel: "16:9",
    promptLabel: "Narrative clip",
  },
  {
    id: "seedance-space-travel",
    useCase: "reference-video-generator",
    slug: "reference-video-generator",
    category: "Worldbuilding",
    title: "Space travel sequence",
    titleZh: "宇宙穿梭场景片段",
    description: "A full Seedance 2 clip that moves from stylized terrain into large-scale sci-fi worldbuilding.",
    descriptionZh: "一条完整的 Seedance 2 场景视频，从体素地貌一路推进到更宏观的宇宙世界观。",
    alt: "Seedance 2 full video showing sci-fi worldbuilding and space travel.",
    altZh: "用于展示 Seedance 2 宇宙世界构建与穿梭场景的完整视频案例。",
    afterImage: "/images/gallery/custom/seedance-space-travel.png",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/seedance-space-travel.mp4",
    durationLabel: "15s",
    aspectRatioLabel: "16:9",
    promptLabel: "Full clip",
  },
  {
    id: "seedance-autumn-duel",
    useCase: "storyboard-to-video",
    slug: "storyboard-to-video",
    category: "Action",
    title: "Autumn duel sequence",
    titleZh: "秋林决斗完整片段",
    description: "A complete cinematic action sample with stronger blocking, camera travel, and character momentum.",
    descriptionZh: "一条完整的动作型样片，镜头调度、走位关系和人物动势都更完整。",
    alt: "Seedance 2 full action video showing a duel in an autumn forest.",
    altZh: "用于展示 Seedance 2 秋林决斗镜头的完整动作视频案例。",
    afterImage: "/images/gallery/custom/seedance-autumn-duel.png",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/seedance-autumn-duel.mp4",
    durationLabel: "13s",
    aspectRatioLabel: "16:9",
    promptLabel: "Full clip",
  },
  ...kieSeedanceSamples,
  {
    id: "product-cinematic",
    useCase: "product-ad-generator",
    slug: "product-ad-generator",
    category: "Commercial",
    title: "Product reveal sequence",
    titleZh: "产品广告揭幕镜头",
    description: "Turn still product shots and one motion reference into a polished campaign-ready reveal.",
    descriptionZh: "把静态产品图和一段参考运镜，转成更像广告片开场的揭幕镜头。",
    alt: "AI video showcase card for a product reveal workflow.",
    altZh: "用于展示产品广告生成工作流的 AI 视频案例卡片。",
    afterImage: "/images/gallery/generated/ghibli.jpg",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/product-reveal.mp4",
    durationLabel: "05s",
    aspectRatioLabel: "4:5",
    promptLabel: "Prompt + refs",
  },
  {
    id: "dance-transfer",
    useCase: "dance-motion-transfer",
    slug: "dance-motion-transfer",
    category: "Motion",
    title: "Dance motion transfer",
    titleZh: "舞蹈动作迁移",
    description: "Clone choreography timing from reference footage while preserving a fresh character identity.",
    descriptionZh: "沿用参考视频里的舞蹈节奏和动作语言，同时保持新的角色设定。",
    alt: "AI video showcase card for dance motion transfer.",
    altZh: "用于展示舞蹈动作迁移工作流的 AI 视频案例卡片。",
    afterImage: "/images/gallery/generated/webtoon.jpg",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/dance-motion.mp4",
    durationLabel: "05s",
    aspectRatioLabel: "9:16",
    promptLabel: "Motion ref",
  },
  {
    id: "storyboard-previs",
    useCase: "storyboard-to-video",
    slug: "storyboard-to-video",
    category: "Previs",
    title: "Storyboard to previs",
    titleZh: "分镜到预演视频",
    description: "Extend still frames into continuous camera moves for previs, blocking, and scene timing tests.",
    descriptionZh: "把静态分镜延展成连续镜头，用于影视预演、走位和节奏验证。",
    alt: "AI video showcase card for storyboard to video previs.",
    altZh: "用于展示分镜到预演视频工作流的 AI 视频案例卡片。",
    afterImage: "/images/gallery/generated/retro_90s.jpg",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/storyboard-previs.mp4",
    durationLabel: "05s",
    aspectRatioLabel: "4:5",
    promptLabel: "Storyboard",
  },
  {
    id: "image-video-seed",
    useCase: "image-to-video",
    slug: "image-to-video",
    category: "Conversion",
    title: "Image to video seed shot",
    titleZh: "图像转视频起始镜头",
    description: "Use still imagery as a locked visual seed, then push into motion with camera direction and timing.",
    descriptionZh: "先把静态图片当成锁定起始画面，再用运镜和节奏把它推成视频镜头。",
    alt: "AI video showcase card for image to video generation.",
    altZh: "用于展示图像转视频工作流的 AI 视频案例卡片。",
    afterImage: "/images/gallery/generated/cyberpunk.jpg",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/image-to-video.mp4",
    durationLabel: "05s",
    aspectRatioLabel: "16:9",
    promptLabel: "Image seed",
  },
  {
    id: "reference-anything",
    useCase: "reference-video-generator",
    slug: "reference-video-generator",
    category: "Reference",
    title: "Reference-led video generation",
    titleZh: "多参考视频生成",
    description: "Blend images, clips, and audio into a single prompt-driven job instead of relying on text alone.",
    descriptionZh: "把图片、视频和音频一起融入单个任务，而不是只靠一句文字描述。",
    alt: "AI video showcase card for multi-reference video generation.",
    altZh: "用于展示多参考视频生成工作流的 AI 视频案例卡片。",
    afterImage: "/images/gallery/generated/standard.jpg",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/reference-led.mp4",
    durationLabel: "05s",
    aspectRatioLabel: "4:5",
    promptLabel: "Audio + refs",
  },
  {
    id: "video-extension",
    useCase: "video-extension",
    slug: "video-extension",
    category: "Extension",
    title: "Scene extension workflow",
    titleZh: "视频平滑扩写",
    description: "Continue an existing clip with the same scene logic, motion direction, and tonal continuity.",
    descriptionZh: "沿着原视频的场景逻辑、动作方向和画面气质，继续把镜头平滑扩写下去。",
    alt: "AI video showcase card for video extension.",
    altZh: "用于展示视频平滑扩写工作流的 AI 视频案例卡片。",
    afterImage: "/images/gallery/generated/cosplay.jpg",
    beforeThumb: SHARED_BEFORE,
    videoUrl: "/videos/gallery/video-extension.mp4",
    durationLabel: "05s",
    aspectRatioLabel: "9:16",
    promptLabel: "Scene extend",
  },
];

export function getLocalizedGalleryItems(locale: string, useCase?: LandingPageSlug) {
  const filtered = useCase ? galleryItems.filter((item) => item.useCase === useCase) : galleryItems;
  const resolved = filtered.length > 0 ? filtered : galleryItems;

  return resolved.map((item) => ({
    ...item,
    categoryLabel: locale === "zh" ? item.titleZh : item.category,
    titleLabel: locale === "zh" ? item.titleZh : item.title,
    descriptionLabel: locale === "zh" ? item.descriptionZh : item.description,
    altLabel: locale === "zh" ? item.altZh : item.alt,
  }));
}
